### ISSUE TITLE
Styling for A-Z

### ISSUE THREAD

**Issue by sleicester** [the-open-university/ouice#17]
_From @sleicester on December 2, 2014 11:57_

It would be good to get styling for A-Z elements and listings, first let's try get some examples of the HTML we use out there at the moment so we can remain consistent.

_Copied from original issue: the-open-university/student-theme-framework#17_

**Comment by sleicester** [comment]
This is from the intranet

```css
.ou-filter ul li a,
.ou-filter ul li strong,
div.bef-select-as-links div.form-type-bef-link a /* Drupal */ {
	display:inline-block;
	padding:.3em .8em;
	margin:0 .3em 1em 0;
	background-color:#eee;
	border-radius:6px;
	color:#039;
	text-decoration:none;
}

.ou-filter ul li a:hover,
div.bef-select-as-links div.form-type-bef-link a:hover /* Drupal */ {
	background-color:#000;
	color:#fff;
}

.ou-filter ul li strong,
.ou-filter ul li.ou-selected a,
.ou-filter ul li a.active, /* Drupal, standard view markup */
div.bef-select-as-links div.form-type-bef-link.selected a /* Drupal */ {
	background-color: #c36;
	font-weight:bold;
	color:#fff;
	background-image: url(bg-selected.png);
	background-position:center left;
	background-repeat:repeat-x;
}
```
